print('Номер рейса:')
flight_number = input()
print('Название авиакомпании (на русском языке):')
organization_name_rus = input()
print('Название авиакомпании (на английском языке):')
organization_name_eng = input()
print('Город прилета (на русском языке):')
city_rus = input()
print('Город прилета (на английском языке):')
city_eng = input()
print('Заканчивается посадка на рейс', flight_number, organization_name_rus, 'до', city_rus)
print('This is the final boarding call for', organization_name_eng, 'flight', flight_number, 'to', city_eng)